### ISSUE TITLE
Allow priors requests to ask for the FPIT+IT files

### ISSUE THREAD

**Issue by joshua-laughner** [TCCON/auto-priors-rs#33]
After talking to Hayoung, I realized that the EM27 users will probably also want to try using the new CO priors, or even reprocess to have a consistent record. This will require adding in an option to the input files to override the met selection.

I think this should actually be implemented as a configuration option, so we could have something like:

```toml
[[request.allowed_met]]
input_file_key = "it_co_reprocessing"
met_key = "geos_it_co"
end_date = "2024-04-01"
```
which would map to:
```rust
struct AllowedRequestMet {
  input_file_key: String,
  met_key: String,
  start_date: Option<NaiveDate>,
  end_date: Option<NaiveDate>
}
```

If a user requests a met key outside the allowed date range, that is an input error. If there are some valid dates in their request, we could just truncate it.

**Comment by joshua-laughner** [comment]
I've implemented this in cde891b and tested that jobs submitted with the `reanalysis` line in the input file is correctly entered in the database with alternate met & ginput keys. The actual config is a little different than above:

```toml
[requests.allowed_mets.co_reprocessing]
met_key = 'geosit_chm'
ginput_key = 'v1.2.0'
end_date = '2024-04-01'
```

It made more sense to make this a table, rather than a list, because that ensured that the keys won't be duplicated.

It will still be worth testing that this actually uses the alternate met and ginput once I'm ready to let this roll - i.e. submit a job and verify that it gets the IT CO.
