### ISSUE TITLE
Service panicked at 1a during change to standard time.

### ISSUE THREAD

**Issue by joshua-laughner** [TCCON/auto-priors-rs#35]
One of the threads in the service had a panic running at 1a on Nov 3, 2024. This is the hour that gets repeated during the switch from DST to standard time, so mostly likely I am not handling a case of an ambiguous time. Given the service timing configuration (below) it is most likely in the job start, standard site tarball creation, or standard site JSON creation threads, since those are the ones that should have ran at 1a.

```toml
[timing]
disable_met_download = false
met_download_hours = 6

disable_job = false
job_start_seconds = 60
status_report_seconds = 60
lut_regen_days = 1
lut_regen_at = '00:00:00'
delete_expired_jobs_hours = 12
delete_expired_jobs_offset_minutes = 15

disable_std_site_gen = false
std_site_gen_hours = 24
std_site_gen_offset_minutes = 180
std_site_tar_minutes = 30
std_site_json_hours = 1
```
