### ISSUE TITLE
Handle multiple reanalyses sets for automatic generation

### ISSUE THREAD

**Issue by joshua-laughner** [TCCON/auto-priors-rs#36]
Thinking more about how to handle the FPIT met + IT CO, I realized that I need a way to tell the automation to generate multiple files for a given day so that if we add a new standard site that goes back before the GEOS IT transition, it will get both the original FPIT files and the FPIT+IT CO files.

Currently, what makes sense to me is to rework the `requests` and `default_options` parts of the configuration. Currently requests would have subsections like:

```toml
[requests.allowed_mets.it_co]
met_key = "fpit+it"
ginput_key = "v1.2.0"
start_date = 2004-01-01
end_date = 2024-04-01
```

and `default_options` will be:

```toml
[[default_options]]
start_date = '2000-01-01'
end_date = '2024-04-01'
ginput = 'v1.0.6'
met = 'geosfpit'

[[default_options]]
start_date = '2024-04-01'
end_date = '2100-01-01'
ginput = 'v1.2.0'
met = 'geosit'
```

I think the way to handle this is to replace `requests` with `reanalyses` or `processing_configurations` that looks something like

```toml
[processing_configurations.std-fpit]
met = "geosfpit"
ginput = "v1.0.6"
# earliest date allowed to request
start_date = "2000-01-01"
# latest date (exclusive) allowed to request 
end_date = "2024-04-01" 
# first date when sites will automatically get this configuration
# if not given, falls back on start_date
auto_start_date = "2000-01-01"
# last date (exclusive) when sites will automatically get this configuration
# if not given, falls back on end_date
auto_end_date = "2024-04-01"
auto_generate = true
auto_tarball_dest = "/path/to/tarballs"
```

`auto_tarball_dest` would replace `execution.std_sites_tar_output`. `execution.std_sites_output_base` would stay, and we would need to create subdirectories in it for each processing configuration. That's probably best done on startup to avoid a race condition.

`default_options` could then be slightly simplified:

```toml
[[default_options]]
start_date = '2000-01-01'
end_date = '2024-04-01'
processing_configuration = "std-fpit"
```

since now we only need to specify the processing configuration. I think it makes sense to keep defaults separate from the processing configurations, since that gives us more flexibility to switch which configuration is the default without needing the processing configuration to end. So if, for example, in the future we wanted GEOS-CF to take over the chemistry partway through the IT period, but still have an option to use IT only, we could. This also makes it clearer that defaults must have one option per time range.

This will require updates to the database and the standard site jobs table CLI. The standard site jobs database table is going to have to track which processing configuration was used for a given row so that the automation can figure out if other configurations need added. The CLI is going to have to print which configuration its showing. It would probably use the defaults with no other flag, but have a flag to show other configurations.

**Comment by joshua-laughner** [comment]
It's probably worth thinking about how this will interface with GEOS-CF for potential MIR retrievals. The way that will work is we will need to have GEOS-CF _in addition to_ GEOS FP-IT and/or GEOS-IT for whatever time period GEOS-CF is available for. (I think it was circa 2018 on.)

It seems like a cleaner approach that what I do now would be to specify each separate set of files (e.g. FP-IT eta met, FP-IT 2d, FP-IT eta chem, IT eta met, IT 2d, IT eta chem) once in the `[data.download]` section with its own, unique key. This relates to #12 because that `MetSubtype` column is essentially this key. So our new download section would look something like:

```toml
[data.download.geosfpit_eta_met]
product = "geosfpit"
data_type = "met"
levels = "eta"
url_pattern = "..."
basename_pattern = "..." # optional
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = "..."
days_latency = 1

[data.download.geosfpit_2d_met]
product = "geosfpit"
data_type = "met"
levels = "surf"
url_pattern = "..."
basename_pattern = "..." # optional
file_freq_min = 180
earliest_date = "2000-01-01"
download_dir = "..."
days_latency = 1
```

We'd need to add the `ginput_met_key` and `ginput_output_subdir` keys to `processing_configurations` instead of keeping them in the download configuration. The processing configurations would then specify a collection of met files required. So the actual processing configuration section might look like this:

```toml
[processing_configurations.std-fpit]
mets_required = ["geosfpit_eta_met", "geos_fpit_eta_chm", "geos_fpit_2d_met"]
ginput = "v1.0.6"
# earliest date allowed to request
start_date = "2000-01-01"
# latest date (exclusive) allowed to request 
end_date = "2024-04-01" 
# first date when sites will automatically get this configuration
# if not given, falls back on start_date
auto_start_date = "2000-01-01"
# last date (exclusive) when sites will automatically get this configuration
# if not given, falls back on end_date
auto_end_date = "2024-04-01"
auto_generate = true
auto_tarball_dest = "/path/to/tarballs"
ginput_met_key = "fpit-eta"
ginput_output_subdir = "fpit"
```

This would allow me to define one processing configuration that, for example, uses FPIT met and IT CO, and a second configuration that adds GEOS-CF H2CO, O3, and NO2 just with different `mets_required`:

```toml
[processing_configurations.fpit-met-it-co]
mets_required = ["geosfpit_eta_met", "geosfpit_2d_met", "geosit_eta_chm"]
...

[processing_configurations.fpit-met-mir]
mets_required = ["geosfpit_eta_met", "geosfpit_2d_met", "geosit_eta_chm", "geoscf_eta_chm"]
...
```

Something to consider is that I could then either set the "fpit-met-mir" one to automatically generate for all sites, or I could add a column to the site info table that specifies additional processing configurations to generate _for that time period for that site_. This would save space and computing time, since most sites wouldn't need the GEOS-CF profiles, but adds complexity. At least for GEOS-CF, unless NO2, H2CO, or O3 show up in the InGaAs windows, it wouldn't be a big deal to just switch the "forward stream" to IT+CF once it's ready.
